package com.jobtracker.monolith.auth.config;

import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import lombok.extern.slf4j.Slf4j;
import org.springframework.security.oauth2.client.web.AuthorizationRequestRepository;
import org.springframework.security.oauth2.core.endpoint.OAuth2AuthorizationRequest;
import org.springframework.stereotype.Component;

import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Stores OAuth2 authorization requests in a server-side map keyed by the
 * {@code state} parameter — no cookie or HTTP session required.
 *
 * <p>Why state-keyed in-memory storage?
 * <ul>
 *   <li>The app is {@code STATELESS} (JWT), so the default
 *       {@code HttpSessionOAuth2AuthorizationRequestRepository} fails.</li>
 *   <li>Storing a UUID key in a cookie on a 302 redirect is unreliable:
 *       some browsers / CDNs silently drop Set-Cookie headers on redirects.</li>
 *   <li>The OAuth2 {@code state} parameter is already echoed back verbatim
 *       by Google in the callback URL, so it is a perfect natural key.</li>
 * </ul>
 *
 * <p>This is an in-memory store — fine for a single-instance Render deployment.
 * The state value is a securely-random string generated by Spring Security,
 * so it provides the same CSRF protection as before.
 */
@Slf4j
@Component
public class HttpCookieOAuth2AuthorizationRequestRepository
        implements AuthorizationRequestRepository<OAuth2AuthorizationRequest> {

    private final Map<String, OAuth2AuthorizationRequest> requestCache = new ConcurrentHashMap<>();

    @Override
    public OAuth2AuthorizationRequest loadAuthorizationRequest(HttpServletRequest request) {
        String state = request.getParameter("state");
        if (state == null) {
            log.debug("loadAuthorizationRequest: no state parameter in request");
            return null;
        }
        OAuth2AuthorizationRequest authRequest = requestCache.get(state);
        log.debug("loadAuthorizationRequest: state={} found={}", state, authRequest != null);
        return authRequest;
    }

    @Override
    public void saveAuthorizationRequest(OAuth2AuthorizationRequest authorizationRequest,
                                          HttpServletRequest request,
                                          HttpServletResponse response) {
        if (authorizationRequest == null) {
            String state = request.getParameter("state");
            if (state != null) requestCache.remove(state);
            return;
        }
        String state = authorizationRequest.getState();
        requestCache.put(state, authorizationRequest);
        log.debug("saveAuthorizationRequest: saved state={}", state);
    }

    @Override
    public OAuth2AuthorizationRequest removeAuthorizationRequest(HttpServletRequest request,
                                                                   HttpServletResponse response) {
        String state = request.getParameter("state");
        if (state == null) {
            log.debug("removeAuthorizationRequest: no state parameter");
            return null;
        }
        OAuth2AuthorizationRequest authRequest = requestCache.remove(state);
        log.debug("removeAuthorizationRequest: state={} found={}", state, authRequest != null);
        return authRequest;
    }
}
